database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:seed.db
  properties:
    charSet: UTF-8
    foreign_keys: true
views:
  freemarker:
    template_exception_handler: rethrow
    strict_syntax: true
